services:
  trading-bot:
    build:
      context: .
    container_name: trading-bot
    restart: always
    volumes:
      - /home/konomut/.trading:/app/data # Mount the SQLite database volume

volumes:
  sqlite_data: